.*(\s|^)аниме.*:
    dict: anime.txt
.*(\s|^)тупой.*:
    dict: stupid.txt
    private_use: true
.*(\s|^)куда.*:
    dict: where_to.txt
.*(\s|^)молодец.*:
    dict: good_boy.txt
.*(\s|^)умни(чк|ц)а.*:
    dict: good_boy.txt
.*(\s|^)молодчинк?а.*:
    dict: good_boy.txt
.*(\s|^)ты крутой.*:
    dict: good_boy.txt
.*(\s|^)когда.*:
    dict: when.txt
(\s|^)да(\s|$):
    dict: yes.txt
(\s|^)нет(\s|$):
    dict: no.txt
.*тюлен.*что.*думаеш.*:
    dict: opinions_think.txt
    unique: true
    private_use: true
.*тюлен.*как.*относишься.*:
    dict: opinions_think.txt
    unique: true
    private_use: true
.*(\s|^)как.*(\s|^)дела.*:
    dict: howyoudoing.txt
    private_use: true
.*расскажи.*о.*себе.*:
    dict: my_life.txt
    private_use: true
.*тюлен.*:
    dict: dict_general.txt
    private_use: true
.*тюлень.*я.*тебя.*люблю.*:
    dict: love.txt
.*люблю.*тебя.*:
    dict: love.txt
.*а[ха]х.*:
    dict: dict_rofl.txt
.*(\s|^)навальн.*:
    dict: navalny.txt
.*(\s|^)нэвэльн.*:
    dict: navalny.txt
.*(\s|^)путин.*:
    dict: puten.txt
.*(\s|^)путен.*:
    dict: puten.txt
.*(\s|^)ввп.*:
    dict: puten.txt
.*новый.*год.*:
    dict: newyear.txt
.*рождество.*:
    dict: newyear.txt
.*тюлень.*крут.*:
    dict: love.txt
    private_use: true
\Bбот:
    dict: bot.txt
.*(\s|^)что.*(\s|^)делае.*:
    dict: doing.txt
    private_use: true
.*(\s|^)почему.*:
    dict: why.txt
.*(\s|^)зачем.*:
    dict: what_for.txt
.*(\s|^)[гх]де.*:
    dict: where.txt
.*(\s|^)гоу?\s.*:
    dict: go_to.txt
.*(\s|^)репорт\s.*:
    dict: report.txt
.*(\s|^)дот[аук].*:
    dict: dota.txt