blacklist: blacklist.txt

warning_message: Ну хватит, ебаныйрот. Еще немного и бан схватишь.

ban_message: | 
        Друге, ты дурак и бан тебе. Если считаешь что не справедливо - иди жалуйся мне на стенку. Иначе - либо донать на каптчу, либо иди нахуй.
        Донаты кидать нa QIWI +79166317941 или яды https://money.yandex.ru/to/41001705503465 от 30 рублей, с пометкой "на разбан" и вашим айдишником. 
        Все деньги пойдут в сервис решения каптчи 2captcha.com, чтобы тюлень всегда был с вами. C уважением, поддержка.
unban_message: | 
        Спасибо, дружище! Не шали больше. Если со мной что случится - смотри нового меня в группе vk.com/seal_in_vacuum


master_uid: 5180483

warning_limit: 9
ban_limit: 17
decrement: 1

stopwords: 
    - цп.жпг 
    - цп.ави
    - цп.гиф
    - цп.jpg 
    - цп.avi
    - цп.gif
    - детское порно.жпг
    - детское порно.гиф
    - пoрнo c дeтьми.жпг
    - порно_с_детьми.жпг
    - детское порно.ави
    - пoрнo c дeтьми.ави
    - порно_с_детьми.ави
    - детское порно.avi
    - пoрнo c дeтьми.avi
    - порно_с_детьми.avi
    - porn_child.jpg
    - child_porn.jpg
    - child porn.jpg
    - children porn.жпг
    - children porno.jpg
    - children porno.жпг
    - child.porn.jpg



