simple_game: тюлень, хотим в морской бой

qa_game: тюлень, хотим в морской бой с вопросами

stop_game: тюлень, мы закончили морской бой

questions:
    - 1: "2"
    - 2: "37"
    - 3: "зеленый"
    - 4: "1"
    - 5: "р"
    - 6: "уважаемые"
    - 7: "московское"
    - 8: "192"
    - 9: "серый"
    - 10: "а"
    - 11: "4"
    - 12: "214"
    - 13: "1"
    - 14: "10"
    - 15: "73"
    - 16: "10"
    - 17: "37"
    - 18: "красный"
    - 19: "12"
    - 20: "1"
    - 21: "3"
    - 22: "7"
    - 23: "синий"
    - 24: "8"
    - 25: "5"
    - 26: "6"
    - 27: "1"
    - 28: "коричневый"
    - 29: "6"
    - 30: "серый"
    - 31: "синий"
    - 32: "красный"
    - 33: "33"
    - 34: "черный"
    - 35: "6"
    - 36: "белый"
    - 37: "9"
    - 38: "3"
    - 39: "техники"
    - 40: "зеленый"
    - 41: "7"
    - 42: "красный"
    - 43: "1"
    - 44: "зеленый"
    - 45: "33"
    - 46: "5"
    - 47: "8"
    - 48: "желтый"
    - 49: "6"
    - 50: "4"
    - 51: "8"
    - 52: "желтый"
    - 53: "2"
    - 54: "желтый"
    - 55: "1"
    - 56: "2"
    - 57: "2"
    - 58: "черный"
    - 59: "9"
    - 60: "155"

#questions:
#    - 1: "1"
#    - 2: "2"
#    - 3: "3"
#    - 4: "4"
#    - 5: "5"
#    - 6: "6"
#    - 7: "7"
#    - 8: "8"
#    - 9: "9"
#    - 10: "10"
#    - 11: "11"
#    - 12: "12"
#    - 13: "13"
#    - 14: "14"
#    - 15: "15"
#    - 16: "16"
#    - 17: "17"
#    - 18: "18"
#    - 19: "19"
#    - 20: "20"
#    - 21: "21"
#    - 22: "22"
#    - 23: "23"
#    - 24: "24"
#    - 25: "25"
#    - 26: "26"
#    - 27: "27"
#    - 28: "28"
#    - 29: "29"
#    - 30: "30"
#    - 31: "31"
#    - 32: "32"
#    - 33: "33"
#    - 34: "34"
#    - 35: "35"
#    - 36: "36"
#    - 37: "37"
#    - 38: "38"
#    - 39: "39"
#    - 40: "40"
#    - 41: "41"
#    - 42: "42"
#    - 43: "43"
#    - 44: "44"
#    - 45: "45"
#    - 46: "46"
#    - 47: "47"
#    - 48: "48"
#    - 49: "49"
#    - 50: "50"
#    - 51: "51"
#    - 47: "47"
#    - 47: "47"
#    - 47: "47"
#    - 47: "47"
#    - 47: "47"
#    - 47: "47"
#    - 47: "47"
#    - 47: "47"

#questions:
#    - Что было, есть и что будет есть: "ленин"
#    - Как какать быстро: "стоя"
#    - Почему?: "потому что пошел нахуй, вот почему"
#    - А?: "б"
#    - Чо?: "хуй в очо"
#    - Где лучшие тусовки?: "у меня в штанах"
#    - Что ты делал прошлым летом?: "пинал хуи"
#    - Что ты делал прошлым летом?: "пинал хуи"
#    - 1?: "2"
#    - белый?: "черный"
#    - 2?: "3"
#    - 4?: "5"
#    - 6?: "7"
#    - 8?: "9"
#    - 10?: "11"
#    - 12?: "13"
#    - 14?: "15"
#    - 16?: "17"
#    - 18?: "19"
#    - 20?: "21"
#    - 22?: "23"
#    - 24?: "25"
#    - 26?: "27"
#    - 28?: "29"