dialog_1:
    dialog_starter_words_regexps:
        - .*тюлень,? расс?кажи [ао]не[кг]дот.*
        - .*тюлень,? как дела.*
        - .*[ао]не[кг]дот.*
    start_without_starter_words: True
    stage_1_launcher_messages:
        - кому анекдот?
        - хотите анегдот?
        - могу в анекдот, хотите?
        - кому онегдот?
    stage_1_reply_positive_regexps:
        - .*хо(чу|тим).*
        - .*д[ао]вай.*
        - .*рассказывай.*
        - .*расскажи.*
        - .*жги.*
        - \b[ао]га\b
        - \bда\b
        - \bй?еп\b
        - \bмн[еу]\b
        - \bнам\b
    stage_1_reply_negative_regexps:
        - .*\bне хо(чу|тим).*
        - \bнет?\b.*
        - .*н[ие]\s?кому.*
        - \bноу?п\b.*
        - .*на\s*хуй.*
        - .*пиздуй.*
    stage_1_stop_messages:
        - как хотити
        - да и не надо
        - ну и хуй с вами
        - пиздос, анегдотов им не надо епта
        - я пытался
        - пидоры
        - ну епта бля
        - хуле вы такие пассивные
        - ладно, деградируйте дальше сами
        - "ну лан =("
        - "((((((((((((((("
        - козлы
        - сам тогда расскажи епт
        - ну лааадно
    stage_2_launcher_messages:
        - "Сидим вечером семьей на диване перед телевизором. Кот родителей
        (здоровый британец, 6-7 кг) растянулся в кресле.
        Через некоторое время с кресла доносится недовольный мяв.
        Папа вскакивает с дивана, подбегает к коту и аккуратно переворачивает на другой бок.
        Кот зевает и снова засыпает. Видя наши вопросительные взгляды, папа пояснил: Неудобно лежал."

        - "ххх: Девочки, как вы сообщили мужу о своей беременности?\n
        ууу: Сделала аиста из бумаги (оригами), тест вложила в клюв и приклеила на дверь туалета внутри.
        Муж спросил, что это за журавль и почему он курит?"

        - "Екатерина: Ищу попутчика или попутчицу для пробежек в парке (примерно 5-10км). Пожалуйста, в лс.
        Буду рада хорошей компании. :)\n
        Станислав: Я толстый и ленивый, но девушка очень симпатична, можно, я на машине рядом ехать буду?
        Музыку ставить, водички там подать?\n
        Вечная Молодость: А что, так можно было? Я тоже тогда на машине, мало ли кушать захочется,
        а у меня всегда сухарики есть и пивас.\n
        Ирина: А можно я рядом с кем-нибудь в машине буду наблюдать за техникой бега?!\n
        Дмитрий: Место в машине еще есть?"

        - "Муж как-то мылся в ванной на втором этаже (частный дом). Закрылся на замок, а его заклинило.
        Открыть не смогли ни я снаружи, ни он изнутри. Пришлось ему в окно вылезать (там несложно, на крышу веранды).
        Тем же вечером мужу заговорщическим тоном сосед сообщил, что он видел,
        как из нашего окна любовник в одних трусах сбегал. Муж не растерялся, ответил: «Да, знаю, это мой»."

        - "xxxx: Она поехала с тусовкой непьющих веганов в Грузию.
        И жаловалась на отсутствие хвалёного грузинского гостеприимства."

        - "ххх: Заметив дыру на футболке, я уже было передумал заходить и хотел вернуться.
        Но тут она порылась в сумочке и выудив пластырь заклеила дыру с изнанки.
        Оставшиеся видимыми части пластыря закрасила черной ручкой. Все, говорит, пошли.
        Вот тогда то я и понял что это моя будущая жена."

        - "Молодая мамаша с дитём лет полутора идёт по улице и что-то ему рассказывает.
        Прислушиваюсь на обгоне: \"Это дерево ясень, это жёлтая лавочка, это заборчик из палочек,
        эти палочки называются \"пруток стальной горячекатанный квадратного сечения 15мм,
        окрашенный алкидной эмалью в два слоя по грунтовке\", а это котик, он говорит \"мяу\"..."

        - "Звоню в курьерскую службу, чтобы оформить заказ.
        Я: город Санкт-Петербург, Невский проспект, 48, курьер нужен на завтра.\n
        Девушка: у меня в базе нет такого проспекта в Санкт-Петербурге.\n
        Я: О.о как это нет?\n
        Д: я вам ещё раз повторяю, нет такого проспекта в Санкт-Петербурге!\n
        Я: Да как это нет Невского проспекта, в Санкт-Петербурге?\n
        Д (разозлившись): у меня тут в базе на Неф- только «Нефтяная дорога»!!!"

        - "Младший брат сегодня спросил.
        Брат: А правда, что у тебя в университете все вопросы или билеты выдают перед экзаменом?\n
        Я: Да\n
        Брат: Так их же можно все выучить."

        - "xxx: У нас во дворе жила бабка, которую мы называли \"Скутер\" в честь немецкой группы.
        А получила она своё прозвище из-за того, что у неё была внучка Фаина и бабка
        выходила на балкон и орала на всю округу \"ФАЯЯЯ...\""

    stage_2_reply_positive_regexps:
        -.*(эт[оа]?)? ахуенно.*
        -.*хоч(чу|тим) [ие]щ[ёео].*
        -.*ааа.*
        -.*за?е?би?сь?.*
        -.*ап*х*а*.*
        -.*ору.*
        -.*норм.*
        -.*хорош.*
        -.*за?е?би?сь?.*
        -.*[еи]щ[еоё].*
    stage_2_reply_negative_regexps:
        -.*хуйня.*
        -.*тюлень ты тупой.*
        -.*говно.*
        -.*не смешн.*
        -.*чушь.*
        -.*хуита.*
        -.*хватит.*
        -.*ржевский говно.*
    stage_2_stop_messages:
        - как хотити
        - да и не надо
        - ну и хуй с вами
        - пиздос, анегдотов им не надо епта
        - я пытался
        - пидоры
        - ну епта бля
        - хуле вы такие пассивные
        - ладно, деградируйте дальше сами
        - "ну лан =("
        - "((((((((((((((("
        - козлы
        - сам тогда расскажи епт
        - ну лааадно
    stage_3_launcher_messages:
        - "А вот ещё, совсем тупой:\n
        XXX: Я знаю чувака, который в диссере хотел исправить
        \"а потом я дам примеры\" на \"а потом я приведу примеры\", и у него получилось \"а потом я приведу дам\""

        - "А вот ещё, мега тупой:\n
        vvv: Великолепный заголовок \"в контактный зоопарк приехали ядовитые лягушки\"..."

        - "А вот ещё, тупее вы не слышали:\n
        xxx: Помнишь, ты ходил в магазин за картошкой?\n
        yyy: Да. И что, она вся испортилась?\n
        xxx: Нет, она вся свекла. Сходи ещё."

        - "А вот ещё тупее:\n
        Застрял в пробке по дороге на работу, пишу смс начальнику: \"привет, жопа с пробками, опоздаю\".\n
        Отвечает: \"привет, сам жопа с пробками\"."

        - "И ещё тупее:\n
        yyy: у нас спокойный ребенок.\n
        xxx: это ты не слышала, как он орать может!\n
        yyy: при мне не орет.\n
        xxx: а вот ты предложи ему что-нибудь, когда он не хочет.\n
        yyy: мне спокойно говорит, что не хочет.\n
        xxx: а ты еще раз предложи!\n
        yyy: Зачем? Я с первого раза понимаю.."

    stage_3_reply_positive_regexps:
        -.*(эт[оа]?)? ахуенно.*
        -.*хоч(чу|тим) [ие]щ[ёео].*
        -.*ааа.*
        -.*за?е?би?сь?.*
        -.*ап*х*а*.*
        -.*ору.*
        -.*норм.*
        -.*хорош.*
        -.*за?е?би?сь?.*
        -.*[еи]щ[еоё].*
    stage_3_reply_negative_regexps:
        -.*хуйня.*
        -.*тюлень ты тупой.*
        -.*говно.*
        -.*чушь.*
        -.*не смешн.*
        -.*хуита.*
        -.*хватит.*
        -.*ржевский говно.*
    stage_3_stop_messages:
        - как хотити
        - да и не надо
        - ну и хуй с вами
        - пиздос, анегдотов им не надо епта
        - я пытался
        - пидоры
        - ну епта бля
        - хуле вы такие пассивные
        - ладно, деградируйте дальше сами
        - "ну лан =("
        - "((((((((((((((("
        - козлы
        - сам тогда расскажи епт
        - ну лааадно
    stage_4_launcher_messages:
        - кончились, приходите завтра
        - а всо, больше нету
        - хорошего по немногу
        - я выдохся, сорян
        - больш не помню
        - кончились
        - я больше не знаю
        - тупые кончились, остались для полных дегродов
        - твоя очередь
        - ваши версии
        - довай тоже делись
        - сам расскажи уже епта
