dialog_1:
    dialog_starter_words_regexps:
        - .*тюлень,? расс?кажи [ао]не[кг]дот.*
        - .*тюлень,? д[оа]вай [ао]не[кг]дот.*
        - .*тюлень,? х[оа]чу [ао]не[кг]дот.*
    start_without_starter_words: True
    stage_1_launcher_messages:
        - кому анекдот?
        - хотите анегдот?
        - могу в анекдот, хотите?
        - кому онегдот?
    stage_1_reply_positive_regexps:
        - .*хо(чу|тим).*
        - .*д[ао]вай.*
        - .*рассказывай.*
        - .*расскажи.*
        - .*жги.*
        - \b[ао]га\b
        - \bда\b
        - \bй?еп\b
        - \bмн[еу]\b
        - \bнам\b
    stage_1_reply_negative_regexps:
        - .*\bне хо(чу|тим).*
        - \bнет?\b.*
        - .*н[ие]\s?кому.*
        - \bноу?п\b.*
        - .*на\s*хуй.*
        - .*пиздуй.*
        - .*не над[оа].*
        - .*за(дол|еб|др)ал.*
    stage_1_stop_messages:
        - как хотити
        - да и не надо
        - ну и хуй с вами
        - пиздос, анегдотов им не надо епта
        - я пытался
        - пидоры
        - ну епта бля
        - хуле вы такие пассивные
        - ладно, деградируйте дальше сами
        - "ну лан =("
        - "((((((((((((((("
        - козлы
        - сам тогда расскажи епт
        - ну лааадно
    stage_2_launcher_messages:
        - "ПРИВЕЛИ В ЦЕРКОВЬ НАСИЛЬНО\n
            @\n
            ПОП ПОЁТ\n
            @\n
            ГОСПОДУ ПОМОЛИМСЯ\n
            @\n
            ПЕРЕКРИКИВАЕШЬ ЕГО:\"В ЖОПУШКУ ПОДОЛБИМСЯ\"\n
            @\n
            БАБКИ ДЕРЖАЛИ - ПОП БИЛ КАДИЛОМ ПО ЕБАЛУ\n"

        - "В Макдональдсе, за столик подсаживается папа с сыном. Сыну где–то лет десять. Ребенок начинает есть и предлагает попробовать отцу.\n
            Папа, погладил сына по голове, и так ласково:\n
            — Да не ем я это говно, сынок"

        - "Идет мужик по пустыне, вымотался весь, видит оазис и там шикарный отель, но стоит табличка \"Пускаем только черных\"\n
            Ну, он взял гуталином намазался — пустили. Вечером он попросил партье его разбудить пораньше, чтобы дальше идти.\n
            На утро его разбудили, он и пошел дальше.\n
            Идет несколько дней, опять выходит на оазис с отелем, только табличка — \"Пускаем только белых\".\n
            Он думает: \"Говно вопрос — сейчас смою гуталин и зайду\"
            Подошел к фонтану, трет–трет — нихуя отмыть не может.
            Оказывается, портье не того негра разбудил."

        - "Муж как-то мылся в ванной на втором этаже (частный дом). Закрылся на замок, а его заклинило.
        Открыть не смогли ни я снаружи, ни он изнутри. Пришлось ему в окно вылезать (там несложно, на крышу веранды).
        Тем же вечером мужу заговорщическим тоном сосед сообщил, что он видел,
        как из нашего окна любовник в одних трусах сбегал. Муж не растерялся, ответил: «Да, знаю, это мой»."

        - "Посадили гражданского активиста на 15 суток за участие в несанкционированном митинге. Заходит он в камеру, а зэки ему говорят:\n
        — У нас тут театральная постановка. Будешь участвовать?\n
        — Да, — говорит активист.\n
        — Есть роли мамы и папы. Кем будешь.?\n
        — Папой. А какой сценарий?\n
        — Очень простой: Приходит папа с митинга Навального и сразу начинает сосать у мамы хуй."

        - "Съела лиса просроченый колобок.\n
        Так лису ещё никогда не просрачивало!"

        - "Весна. По доpоге идут паpень с девушкой. Вокpуг кpасота, птички поют, чеpвячки пеpеплетаются.
        Паpень намекает, мол, давай зайдем в лесок. Девушка в ответ кивает головой.
        Заходят они в лесок, нашли подходящую полянку, pазложились, ну и долбятся.
        Hо вдpуг, паpню pезко пpиспичило по малой. Он и говоpит:\n
        - Слушай, доpогая, я сейчас отлучусь в кусты, отолью, веpнусь и мы с тобой пpодолжим.\n
        - Ты что, не знаешь? В этом лесу живет быстpый Гонзалес!\n
        - ...?\n
        - Ну, как только ты отойдешь, он прибежит и начнет меня ебать.\n
        - Ну хорошо, тогда я отвернусь, отолью, повернусь и мы с тобой продолжим.\n
        - Нет, ты не понял - это быстрый, очень быстрый Гонсалес.\n
        - Неужели такой быстрый?\n
        - Да пиздец какой быстрый.\n
        - Хорошо. Тогда я выну, отверну в сторону, отолью, а тебе заткну пальчиком, чтоб Гонсалес ничего не сделал.\n
        Девушка, подумав, соглашается. Парень достает, отворачивает, и засовывает палец в жопу быстрому Гонсалесу.\n\n
        Идут двое влюбленных по лесу, выходят на опушку. Парень предлагает девушке заняться сексом, та ему в ответ:\n
        — Ты что, разве не знаешь — в этом лесу живет Медленный Родригез!\n
        — Ну и что?\n
        — И правда.\n
        Занимаются они сексом и уходят. На следующий день грибник собирает на опушке грибы, нагибается за сыроежкой
        и засовывает палец в жопу Медленному Родригезу."

        - "Крутится-вертится спиннеръ въ рукъ,\n
        Жарится-парится вэйпъ въ рюкзакъ,\n
        Майнится-мается новый биткойнъ,\n
        Мчитъ кавалера сегвей вороной!\n\n
        Гдъ тотъ локейшенъ, мнъ Сири скажи,\n
        Гдъ фитоняша, чьи луки свъжи?\n
        Вотъ тотъ коворкингъ, вотъ крафтовый баръ\n
        Вотъ фитоняша, чьи луки - пожаръ!"

        - "Когда мне было 20 лет, и я ходил играть на гитаре дядя всё время как-бы невзначай крутился возле репточки,
        и всё спрашивал, что ты там затих, почему тебя не слышно? первый раз я не ответил, так он начал ломиться
        в дверь, и орать, что ты там молчишь, что с тобой? начал материться, и говорить, что вообще дверь с петель
        снимет, алсо, дядя ругался, если я играю и не делаю соло, причём не просто вконце песни, а непосредственно
        после каждого припева, мотивировал это тем, что \"одни нули\", и сам потом мне говорил:
        вот я нули поиграю и соло запиливаю, и ты так делай! однажды мы с Мишей играть концерт пошли, и слышу,
        дядя где-то у стеков встал за кулисами, ну я дилэй покрутил, и на пол накарачики присел, а там щель
        очень широкая снизу между кабами, ну я в щель и смотрю, а там дядя на карачиках сидит и в щель смотрит,
        и мне говорит: ты чё? ебанутый? чё ты там делаешь? дядя кстати всё время какие-то травы пьёт, чтобы играть
        быстро, гоняет свипы по 5 раз в день, а потом говорит, что руки жжёт, и ещё флойдом балуется он.
        пиздец короче! реальная история. я Джейк Боуэн"

        - "Гена и Чебурашка попали в тюрьму. \n
        — Гена, а нас будут брить? \n
        — Вон у крысы спроси.\n
        — Крыса, а нас будут брить?\n
        — Да."

    stage_2_reply_positive_regexps:
        -.*(эт[оа]?)? ахуенно.*
        -.*хоч(чу|тим) [ие]щ[ёео].*
        -.*ааа.*
        -.*за?е?би?сь?.*
        -.*ап*х*а*.*
        -.*ору.*
        -.*норм.*
        -.*хорош.*
        -.*за?е?би?сь?.*
        -.*[еи]щ[еоё].*
    stage_2_reply_negative_regexps:
        -.*хуйня.*
        -.*тюлень ты тупой.*
        -.*говно.*
        -.*не смешн.*
        -.*чушь.*
        -.*хуита.*
        -.*хватит.*
        -.*ржевский говно.*
    stage_2_stop_messages:
        - как хотити
        - да и не надо
        - ну и хуй с вами
        - пиздос, анегдотов им не надо епта
        - я пытался
        - пидоры
        - ну епта бля
        - хуле вы такие пассивные
        - ладно, деградируйте дальше сами
        - "ну лан =("
        - "((((((((((((((("
        - козлы
        - сам тогда расскажи епт
        - ну лааадно
    stage_3_launcher_messages:
        - "А вот ещё, совсем тупой:\n
        Объезжает генерал части на фронте перед атакой. И тут рядовой задаёт ему вопрос: \n
        — Скажите, товарищ генерал, а правда что война?\n
        — Всем война, а тебе на ебло говна, - сказал генерал, и насмерть уебался с кобылы."

        - "А вот ещё, мега тупой:\n
        Шла девочка с дедушкой вдоль речки. Смотрят, гавно плывет. Ну, а девочка и спрашивает: \n
        - Откуда оно?\n
        А дедушка говорит:\n
        - Было это давно. Жил принц и принцесса. Принц уехал воевать, а принцесса, подумав, что его убьют,
        утопилась в этой самой речушке.\n
        Спрашивает вновь девочка:\n
        - А гавно-то откуда?\n
        - А я ебу? Насрал кто-то."

        - "А вот ещё, тупее вы не слышали:\n
        Эмиль Артин был известен за крайне понятные лекции, которые он читал не пользуясь никакими записями.\n
        Однажды, посреди доказательства, он внезапно запнулся и сказал: \"Это заключение тривиально\".\n
        Через несколько секунд он повторил: \"Оно тривиально, но я не помню почему\".\n
        Он подумал над вопросом ещё минуту и сказал: \"Я знаю что оно тривиально, но я не могу понять его\".\n
        Поколебавшись ещё несколько секунд он наконец сказал: \"Извините, мне нужно заглянуть в свои записи\".\n
        Затем он вышел аудитории и вернувшись через 10 минут сказал: \"Бля, реально тривиально\"."

        - "А вот ещё тупее:\n
        Тонет корабль. Все пассажиры плавают в воде, только головы видны. А на лодке плавают матросы и вытаскивают
        пассажиров за волосы в лодку. И вдруг им попадается совершенно лысая голова. Один из матросов берет весло,
        бъет им по лысине и говорит:\n
        - Нам тут блять не до шуток.."

        - "И ещё тупее:\n
        Охотник собрался на охоту в тайгу, местности не знает, берёт с собой проводника из местных.
        Идут по тайге — проводник впереди, прорубает чащу топором с длинным топорищем,
        охотник идёт за ним с ружьём, в спину дышит.\n
        Вдруг – хуякс! – из чащи медведь навстречу. Проводник замер с поднятым топором, медведь тоже замер,
        смотрят друг на друга.\n
        Проводник, не оборачиваясь, говорит охотнику вполголоса:\n
        — Иди сюда…\n
        Сзади тишина, он повторяет:\n
        — И–ди сю–да…\n
        Сзади опять тишина, он в третий раз уже аж шипит:\n
        — Иди сюда, блядь!\n
        Сзади охотник с возмущением:\n
        — Нахуй ты его зовёшь?!"

        - "Могу ещё тупее:\n
        Трахает муж жену, она от удовольствия расслабилась, да как пернет.\n
        Муж спрашивает:\n
        - Это ты пернула?\n
        - Нет, это кровать скрипнула.\n
        - А почему у меня хуй в говне?\n
        - Так наш сын уже два часа как на дискотеке."

        - "Вот ещё, тупее точно не слышали:\n
        Поймали три брата золотую рыбку. Она взмолилась:\n
        – Отпустите меня, добры молодцы, и тогда исполню каждому по три любых желания.\n
        Посовещались братья и решили рыбку отпустить.\n
        Молвит старший брат:\n
        – Хочу мешок золота.\n
        Молвит средний:\n
        – И я хочу мешок золота.\n
        Младший же брат говорит:\n
        – А я хочу, чтобы рука тряслась!\n
        Посмотрели все на него, как на дурачка, но ничего не сказали. Загадывают дальше.
        Старший и средний пожелали для себя кареты резные, позолоченные от крыши до колёс, какие во всём королевстве
        не сыщешь, а младший опять чудит:\n
        – Хочу, – говорит, – чтобы нога тряслась!\n
        Переглянулись братья. \"Ну, – думают, – точно спятил\".
        Загадывают последнее желание. Старший захотел сделаться сильным, как лев, а средний попросил ещё два
        мешка золота, потому как жаден был до денег. А младший и говорит:\n
        – Хочу, чтобы голова тряслась!\n
        Исполнила рыбка их желания.\n
        Возвращаются молодцы домой. Старший и средний радуются, предвкушают, как будут жить они в роскоши,
        как не будет в их жизни горести, а младший идёт, трясётся и думает:\n
        – Бля, меня внатуре залепило!"

    stage_3_reply_positive_regexps:
        -.*(эт[оа]?)? ахуенно.*
        -.*хоч(чу|тим) [ие]щ[ёео].*
        -.*ааа.*
        -.*за?е?би?сь?.*
        -.*ап*х*а*.*
        -.*ору.*
        -.*норм.*
        -.*хорош.*
        -.*за?е?би?сь?.*
        -.*[еи]щ[еоё].*
    stage_3_reply_negative_regexps:
        -.*хуйня.*
        -.*тюлень ты тупой.*
        -.*говно.*
        -.*чушь.*
        -.*не смешн.*
        -.*хуита.*
        -.*хватит.*
        -.*ржевский говно.*
    stage_3_stop_messages:
        - как хотити
        - да и не надо
        - ну и хуй с вами
        - пиздос, анегдотов им не надо епта
        - я пытался
        - пидоры
        - ну епта бля
        - хуле вы такие пассивные
        - ладно, деградируйте дальше сами
        - "ну лан =("
        - "((((((((((((((("
        - козлы
        - сам тогда расскажи епт
        - ну лааадно
    stage_4_launcher_messages:
        - кончились, приходите завтра
        - а всо, больше нету
        - хорошего по немногу
        - я выдохся, сорян
        - больш не помню
        - кончились
        - я больше не знаю
        - тупые кончились, остались для полных дегродов
        - твоя очередь
        - ваши версии
        - довай тоже делись
        - сам расскажи уже епта
